export const APPLICATION_LOADED = "APPLICATION_LOADED";
export const ERROR = "ERROR";

export const RELOAD_POSTS = "RELOAD_POSTS";
export const RELOAD_AUTHORS = "RELOAD_AUTHORS";
export const RELOAD_CATEGORIES = "RELOAD_CATEGORIES";

export const CATEGORY_ADDED_TO_POST = "CATEGORY_ADDED_TO_POST";
export const POST_SAVE = "POST_SAVE";
export const POST_UPDATE = "POST_UPDATE";
export const ADD_POST_FORM_VALUE_CHANGED = "ADD_POST_FORM_VALUE_CHANGED";
export const EDIT_POST_FORM_VALUE_CHANGED = "EDIT_POST_FORM_VALUE_CHANGED";
export const VIEW_POST = "VIEW_POST";
export const EDIT_POST = "EDIT_POST";

export const ADD_COMMENT_FORM_VALUE_CHANGED = "ADD_COMMENT_FORM_VALUE_CHANGED";
export const SAVE_COMMENT = "SAVE_COMMENT";
export const COMMENT_ADDED = "COMMENT_ADDED";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_POST = "DELETE_POST";
export const DELETE_AUTHOR = "DELETE_AUTHOR";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";