export const APPLICATION_STARTED = "APPLICATION_STARTED";
export const RELOAD_POSTS = "RELOAD_POSTS";
export const RELOAD_AUTHORS = "RELOAD_AUTHORS";
export const RELOAD_CATEGORIES = "RELOAD_CATEGORIES";
export const ERROR = "ERROR";
export const CATEGORY_ADDED_TO_POST = "CATEGORY_ADDED_TO_POST";
export const POST_SAVE = "POST_SAVE";