export const APPLICATION_STARTED = "APPLICATION_STARTED";
export const RELOAD_POSTS = "RELOAD_POSTS";
export const RELOAD_AUTHORS = "RELOAD_AUTHORS";
export const RELOAD_CATEGORIES = "RELOAD_CATEGORIES";
export const RELOAD_PERIODS = "RELOAD_PERIODS";
export const ERROR = "ERROR";